[project]
name = "Meal_Journal_API"
version = "0.1.0"
description = "API for meal journal application"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.8",
    "mangum>=0.19.0",
]

[dependency-groups]
dev = [
    "fastapi[standard]>=0.115.8",
]
